.\"
.\" Copyright (c) 2019  Joachim Nilsson <troglobit@gmail.com>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd May 14, 2023
.Dt backlight 1
.Sh NAME
.Nm backlight
.Nd
control backlight brightness of laptops in Linux
.Sh SYNOPSYS
.Nm
.Op Fl hv
.Op Ar up | down
.Sh DESCRIPTION
.Nm
supports one display, the built-in laptop display.  It uses the first
one it finds when scanning
.Pa /sys/class/backlight/*/brightness .
.Pp
Brightness is controlled using an exponential scale to provide a smooth
transition from max to min.
.Sh OPTIONS
.Bl -tag -width down -compact
.It Fl h
Show program help text
.It Fl v
Show program version
.El
.Sh COMMANDS
.Bl -tag -width down -compact
.It up
Increase brightness
.It down
Decrease brightness
.Sh FILES
.Pa /sys/class/backlight/*/brightness .
.Sh SEE ALSO
.Lk https://github.com/troglobit/backlight/
.Sh AUTHORS
Joachim Nilsson
.Aq mailto:troglobit@gmail.com .
